name: 'publish'
on:
  push:
    branches: master
jobs:
  deploy_webhook:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Trigger webhook
        run: curl -X POST 'https://api.vercel.com/v1/integrations/deploy/prj_rL0Oc4TkGxVAYnqsMzsoRP040LM7/AyZwLTfuRY' 
